# This file controls the AWS CodeBuild

version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
#    - mvn clean prepare-package war:exploded
    - mvn package
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - mv target/aws-elastic-beanstalk-example-2-0.0.4-SNAPSHOT.war aws-elastic-beanstalk-example-2-0.0.4-SNAPSHOT.war
    - echo "moved to present directory....."
#    - mv target/deploy ./
artifacts:
  files:
#    - deploy/**/*
#    - '**/*'
    - target/aws-elastic-beanstalk-example-2-0.0.4-SNAPSHOT.war
    - echo "line ---------------------- 1"
    - .ebextensions/**/*
    - echo "line..................... 2"
  base-directory: 'target/aws-elastic-beanstalk-example-2-0.0.4-SNAPSHOT'
    